import streamlit as st
import asyncio
import json
from datetime import datetime
from pathlib import Path
import sys
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")
sys.path.append(str(Path(__file__).parent.parent))

from agent.graph import build_graph
from agent.models import AgentConfig, AgentState
from agent.results import export_results


# ── Helper functions ──────────────────────────────────────────────────────────

def log_box(log_lines: list[str]) -> str:
    html = "<br>".join(log_lines[-20:])
    return (
        f'<div style="background:#0e1117;color:#c8d0da;font-family:monospace;'
        f'font-size:0.78rem;padding:0.75rem;border-radius:6px;height:200px;'
        f'overflow-y:auto">{html}</div>'
    )


def render_summary(r: dict):
    summary = r.get("summary", {})
    st.markdown("#### Summary")
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("Tests generated", summary.get("test_cases_generated", 0))
    m2.metric("Tests executed",  summary.get("tests_executed", 0))
    m3.metric("Bugs detected",   summary.get("bugs_detected", 0))
    m4.metric("False positives", summary.get("false_positives", 0))
    m5.metric("Tokens used",     f"{r.get('meta', {}).get('token_usage', 0):,}")


def classify_eval(ev: dict) -> str:
    """Classify evaluation as reflection, white-box, or standard."""
    test_id  = ev.get("test_id", "")
    endpoint = ev.get("endpoint", "")
    if test_id.startswith("WB-"):
        return "white_box"
    if test_id.startswith("TC-R"):
        return "reflection"
    if endpoint == "source_code":
        return "white_box"
    return "standard"


def filter_evaluations(evals: list[dict], bug_filter: str, source_filter: str) -> list[dict]:
    # Bug filter
    if bug_filter == "Bugs only":
        evals = [e for e in evals if e.get("bug_detected")]
    elif bug_filter == "Passed only":
        evals = [e for e in evals if not e.get("bug_detected")]

    # Source filter — no reflection here since they aren't executed
    if source_filter == "Standard only":
        evals = [e for e in evals if classify_eval(e) == "standard"]
    elif source_filter == "White-box only":
        evals = [e for e in evals if classify_eval(e) == "white_box"]

    return evals

def render_reflection_cases(r: dict):
    """Show reflection test cases that were generated but not executed."""
    all_cases = r.get("test_cases", [])
    reflection_cases = [tc for tc in all_cases if tc.get("id", "").startswith("TC-R")]

    if not reflection_cases:
        return

    st.markdown("---")
    st.markdown(f"#### 🔄 Reflection test cases — {len(reflection_cases)} generated (not executed)")
    st.caption("These cases were generated by the reflection node based on evaluation results but were not executed in this iteration.")

    for tc in reflection_cases:
        with st.expander(f"🔄 {tc.get('id','')} — {tc.get('method','')} {tc.get('endpoint','')}"):
            c1, c2 = st.columns(2)
            c1.markdown(f"**Expected status:** `{tc.get('expected_status','')}`")
            c2.markdown(f"**Method:** `{tc.get('method','')}`")
            st.markdown(f"**Rationale:** *{tc.get('rationale','')}*")
            if tc.get("payload"):
                st.json(tc.get("payload"))
def render_evaluation_card(ev: dict):
    bug      = ev.get("bug_detected", False)
    kind     = classify_eval(ev)
    kind_icon = {"white_box": "🔍", "reflection": "🔄", "standard": "🔵"}.get(kind, "")
    bug_icon  = "🐛" if bug else "✅"

    label = (
        f"{bug_icon} {kind_icon} "
        f"{ev.get('test_id','')} — {ev.get('endpoint','')}"
    )
    with st.expander(label):
        c1, c2, c3 = st.columns(3)
        c1.markdown(f"**Bug detected:** {'Yes' if bug else 'No'}")
        c2.markdown(f"**Status received:** `{ev.get('status_received','')}`")
        c3.markdown(f"**Type:** {kind.replace('_',' ').title()}")
        st.markdown(f"**Verdict:** {ev.get('verdict','')}")
        st.markdown(
            f"**LLM Reasoning:** *{ev.get('reasoning') or ev.get('resoning','')}*"
        )


def render_results_tab(r: dict):
    render_summary(r)
    st.markdown("---")

    col_f1, col_f2 = st.columns(2)
    with col_f1:
        bug_filter = st.selectbox("Filter by result", ["All", "Bugs only", "Passed only"])
    with col_f2:
        source_filter = st.selectbox("Filter by source", ["All", "Standard only", "White-box only"])

    evals = filter_evaluations(r.get("evaluations", []), bug_filter, source_filter)
    bugs_shown = sum(1 for e in evals if e.get("bug_detected"))
    st.markdown(f"#### Evaluations — {len(evals)} shown ({bugs_shown} bugs)")

    for ev in evals:
        render_evaluation_card(ev)

    render_reflection_cases(r)    # add this

    st.markdown("---")
    st.download_button(
        "⬇ Download JSON",
        data=json.dumps(r, indent=2),
        file_name=f"agent_{r.get('meta',{}).get('target','')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
        mime="application/json",
        use_container_width=True
    )





# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="AI Testing Agent",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.markdown("## Configuration")

    target = st.selectbox(
        "Target app",
        ["python", "java", "python_os", "java_os"],
    )

    mode = st.selectbox(
        "Testing mode",
        ["black", "white", "hybrid"],
        help="black: API only | white: source code only | hybrid: both"
    )

    base_url = st.text_input(
        "Base URL",
        value="http://localhost:8000" if "python" in target else "http://localhost:8080"
    )

    spec_url = st.text_input(
        "OpenAPI spec URL",
        value=f"{base_url}/"
    )

    st.markdown("---")
    st.markdown("#### Agent settings")

    max_iter     = st.slider("Max iterations", 1, 5, 1)
    token_budget = st.number_input(
        "Token budget",
        min_value=5000, max_value=100000, value=30000, step=5000
    )

    st.markdown("---")
    st.markdown("#### Input files")

    requirements_file = st.file_uploader(
        "Requirements file", type=["txt", "md"],
        help="Optional: business rules and auth info"
    )
    source_code_file = st.file_uploader(
        "Source code file", type=["py", "java"],
        help="Optional: for white-box or hybrid mode"
    )

    if requirements_file:
        st.success(f"✓ {requirements_file.name}")
    if source_code_file:
        st.success(f"✓ {source_code_file.name}")

    st.markdown("---")
    run_btn = st.button("▶ Run agent", type="primary", use_container_width=True)


# ── Main ──────────────────────────────────────────────────────────────────────

st.title("AI Testing Agent")
st.caption("LangGraph-based agentic REST API testing")

tab_run, tab_results = st.tabs(["Run", "Results"])

# ── Tab: Run ──────────────────────────────────────────────────────────────────
with tab_run:
    col_cfg, col_log = st.columns([1, 2])

    with col_cfg:
        st.markdown("#### Current config")
        st.markdown(f"**Target:** `{target}`")
        st.markdown(f"**Mode:** `{mode}`")
        st.markdown(f"**Base URL:** `{base_url}`")
        st.markdown(f"**Max iterations:** {max_iter}")
        st.markdown(f"**Token budget:** {token_budget:,}")
        if requirements_file:
            st.markdown(f"**Requirements:** `{requirements_file.name}`")
        if source_code_file:
            st.markdown(f"**Source code:** `{source_code_file.name}`")

    with col_log:
        st.markdown("#### Agent log")
        log_placeholder = st.empty()
        log_placeholder.markdown(
            log_box(["Waiting for run…"]),
            unsafe_allow_html=True
        )

    if run_btn:
        requirements = requirements_file.read().decode("utf-8") if requirements_file else None
        source_code  = source_code_file.read().decode("utf-8", errors="ignore") if source_code_file else None

        config = AgentConfig(
            base_url=base_url,
            spec_url=spec_url,
            target=target,
            mode=mode,
            max_iterations=max_iter,
            token_budget=token_budget,
        )

        initial_state: AgentState = {
            "config": config,
            "spec": {},
            "test_cases": [],
            "results": [],
            "evaluations": [],
            "iteration": 0,
            "new_cases_this_iteration": 0,
            "token_usage": 0,
            "termination_reason": None,
            "requirements": requirements,
            "source_code": source_code,
        }

        log_lines = []

        def append_log(msg: str):
            ts = datetime.now().strftime("%H:%M:%S")
            log_lines.append(f"[{ts}] {msg}")
            log_placeholder.markdown(
                log_box(log_lines),
                unsafe_allow_html=True
            )

        append_log(f"Starting — target: {target}, mode: {mode}")
        if requirements:
            append_log(f"Requirements loaded ({len(requirements)} chars)")
        if source_code:
            append_log(f"Source code loaded ({len(source_code)} chars)")

        with st.spinner("Agent running…"):
            try:
                append_log("Fetching OpenAPI spec…")
                graph = build_graph()
                append_log("Graph compiled — running pipeline…")
                final_state = asyncio.run(graph.ainvoke(initial_state))
                append_log(f"✓ Done — {final_state['iteration']} iteration(s)")
                append_log(f"Tokens used: {final_state['token_usage']:,}")
                output = export_results(final_state, target)
                st.session_state["results"] = output
                st.success("Run complete — see Results tab")
            except Exception as e:
                append_log(f"✗ Error: {str(e)[:150]}")
                st.error(f"Agent error: {e}")

# ── Tab: Results ──────────────────────────────────────────────────────────────
with tab_results:
    if "results" not in st.session_state:
        st.info("No results yet. Configure and run the agent from the Run tab.")
    else:
        render_results_tab(st.session_state["results"])

